<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Platforms>x64</Platforms>
    <RootNamespace>captcho.Tester</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="cs-tester.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\captcho-capture\captcho-capture.csproj" />
  </ItemGroup>
</Project>
